export const vegetables = [
  ['白菜', 'hakusai.png'],
  ['ほうれん草', 'hourensou.png'],
  ['じゃがいも', 'jagaimo.png'],
  ['ケール', 'kale.png'],
  ['金時草', 'kinjisou.png'],
  ['小松菜', 'komatsuna.png'],
  ['空芯菜', 'kuusinsai.png'],
  ['モロヘイヤ', 'moroheiya.png'],
  ['ナス', 'nasu.png'],
  ['ネギ', 'negi.png'],
  ['人参', 'ninjin.png'],
  ['ピーマン', 'piman.png'],
  ['ロマネスコ', 'romanesco.png'],
  ['ルッコラ', 'rucola.png'],
  ['春菊', 'syungiku.png'],
  ['玉ねぎ', 'tamanegi.png'],
  ['てんさい', 'tensai.png'],
  ['トマト', 'tomato.png'],
].map(x => [x[0], '/static/images/' + x[1]]);